import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "./components/navigation";
import Footer from "./components/footer";


export const metadata = {
  title: "PMG previewer",
  description: "Generated by NEXT",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className=""
      >
        <Navbar/>
        {children}
<Footer/>
      </body>
    </html>
  );
}
