import "./globals.css";
import Navbar from "./components/navigation";
import Footer from "./components/footer";
import Inspiration from "./components/inspiration";


export const metadata = {
  title: "PMG previewer",
  description: "Generated by NEXT",
  icons: {
    icon: "/favicon.svg",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className="mt-4"
      >
        <Navbar/>
        {children}
        <Inspiration/>
<Footer/>
      </body>
    </html>
  );
}
